
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: 5432
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: turbo_dev1
  username: turbo_dev1
  password: 123456

  
test:
  <<: *default
  database: turbo_test1
  username: turbo_test1
  password: password1234
  


production:
  <<: *default
  database: turbo_prod1
  username: turbo_prod1
  password: password12345


